# Show colors in console output (and log files)
color-logs: true

# Debug output to console (and log files)
debug-mode: false

# Language file (for translations)
language-file: lang-en.yml

enabled-worlds:
- world

supply-claimbook: true

claims:
    minimum-width: 5
    minimum-area: 100
    maximum-per-player: -1
    auto-radius: 5

claim-blocks:
    accrued-per-hour: 100
    accrued-idle-percent: 50
    idle-threshold: 3

claim-tool:
    material: STICK
    data: 0
    name: ""
    lore: []

inspect-tool:
    material: FEATHER
    data: 0
    name: ""
    lore: []

dynmap:
    layer:
        name: "Pl3xClaims"
        priority: 2
        hidebydefault: false
    minzoom: 0
    info-window: '<div class="infowindow">Claim Owner: <span style="font-weight:bold;">%owner%</span><br/>Permission Trust: <span style="font-weight:bold;">%managers%</span><br/>Trust: <span style="font-weight:bold;">%builders%</span><br/>Container Trust: <span style="font-weight:bold;">%containers%</span><br/>Access Trust: <span style="font-weight:bold;">%accessors%</span></div>'
    admin-window: '<div class="infowindow"><span style="font-weight:bold;">Administrator Claim</span><br/>Permission Trust: <span style="font-weight:bold;">%managers%</span><br/>Trust: <span style="font-weight:bold;">%builders%</span><br/>Container Trust: <span style="font-weight:bold;">%containers%</span><br/>Access Trust: <span style="font-weight:bold;">%accessors%</span></div>'
    use3dregions: false
    visibleregions: []
    hiddenregions: []
    regionstyle:
        strokeColor: "#FF0000"
        strokeOpacity: 0.8
        strokeWeight: 3
        fillColor: "#FF0000"
        fillOpacity: 0.35
    ownerstyle:
        administrator:
            strokeColor: "#0000FF"
            fillColor: "#0000FF"
