# Show colors in console output (and log files)
color-logs: true

# Debug output to console (and log files)
debug-mode: false

# Language file (for translations)
language-file: lang-en.yml

# Title timings (in ticks)
title:
    fade-in: 10
    stay: 30
    fade-out: 20
