name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Paper Plugin
author: BillyGalbreath
softdepend:
- Vault
- ProtocolLib

commands:
    pl3xclaims:
        description: Reload configs
        usage: /<command> (reload)
        aliases:
        - claims

permissions:
    command.pl3xclaims:
        description: Allows reload configs
        default: op
