name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Paper Plugin
author: BillyGalbreath

commands:
    claim:
        description: Creates a claim centered around your current location
        permission: command.claim
        usage: /<command> (radius)
        aliases:
        - makeclaim
        - createclaim
        - newclaim

    abandonclaim:
        description: Deletes a claim
        permission: command.abandonclaim
        usage: /<command> (force)
        aliases:
        - unclaim
        - declaim
        - disclaim
        - removeclaim
        - abandontoplevelclaim
        - abandonparentclaim
    abandonallclaims:
        description: Deletes ALL your claims
        permission: command.abandonallclaims
        usage: /<command>
        aliases:
        - unclaimall
        - declaimall
        - disclaimall
        - removeallclaims

    trust:
        description: Manage your claim(s) trustlist
        permission: command.trust
        usage: /<command> [player | public]
        aliases:
        - containertrust
        - accesstrust
        - permissiontrust
        - untrust
    trustlist:
        description: List permissions for the claim you're standing in
        permission: command.trust
        usage: /<command>
        aliases:
        - trustslist
        - listtrust
        - listtrusts

    adminclaims: Switches the claim tool to admin mode, used to create admin claims
        description:
        permission: command.adminclaims
        usage: /<command>
        aliases:
        - adminclaim
        - adminmode
    basicclaims: Switches the claim tool to basic mode, used to create top level claims
        description:
        permission: command.basicclaims
        usage: /<command>
        aliases:
        - basicclaim
        - basicmode
    childclaims:
        description: Switches the claim tool to child mode, used to create child claims
        permission: command.childclaims
        usage: /<command>
        aliases:
        - childclaim
        - childmode
        - subdivideclaims
        - subdivideclaim

    adjustbonusclaimblocks:
        description:
        permission: command.adjustbonusclaimblocks
        usage: /<command>
        aliases: []
    adjustbonusclaimblocksall:
        description:
        permission: command.adjustbonusclaimblocksall
        usage: /<command>
        aliases: []
    setaccruedclaimblocks:
        description:
        permission: command.setaccruedclaimblocks
        usage: /<command>
        aliases: []

    deleteclaim:
        description:
        permission: command.deleteclaims
        usage: /<command>
        aliases: []
    deleteallclaims:
        description:
        permission: command.deleteallclaims
        usage: /<command>
        aliases: []
    deleteclaimsinworld:
        description:
        permission: command.deleteclaimsinworld
        usage: /<command>
        aliases: []
    deletealladminclaims:
        description:
        permission: command.deletealladminclaims
        usage: /<command>
        aliases: []

    extendclaim:
        description:
        permission: command.extendclaim
        usage: /<command>
        aliases: []

    buyclaimblocks:
        description:
        permission: command.buyclaimblocks
        usage: /<command>
        aliases: []
    sellclaimblocks:
        description:
        permission: command.sellclaimblocks
        usage: /<command>
        aliases: []

    trapped:
        description:
        permission: command.trapped
        usage: /<command>
        aliases: []

    ignoreclaims:
        description:
        permission: command.ignoreclaims
        usage: /<command>
        aliases: []

    claimslist:
        description:
        permission: command.claimslist
        usage: /<command>
        aliases: []
    adminclaimslist:
        description:
        permission: command.adminclaimslist
        usage: /<command>
        aliases: []

    transferclaim:
        description:
        permission: command.transferclaim
        usage: /<command>
        aliases: []

    claimbook:
        description:
        permission: command.claimbook
        usage: /<command>
        aliases: []
    claimkit:
        description:
        permission: command.claimkit
        usage: /<command>
        aliases: []

    pl3xclaims:
        description: Reload configs
        permission: command.pl3xclaims
        usage: /<command> (reload)
        aliases:
        - claims

permissions:
    command.claim:
        description: Allows to create claims
        default: op
    command.abandonclaim:
        description: Allows to abandon claims
        default: op
    command.abandonallclaims:
        description: Allows to abandon all claims
        default: op
    command.childclaims:
        description: Allows to create child claims
        default: op
    command.pl3xclaims:
        description: Allows reload configs
        default: op

    claims.overridelimits:
        description: Allows to override configured limits
        default: op

    claims.adminclaims:
        description: Allows to create admin claims
        default: op
    claims.deleteclaims:
        description: Allows to delete any non-admin claims anywhere
        default: op

    claims.visualize:
        description: Allows to visualize claims
        default: true
    claims.visualize.nearby:
        description: Allows to visualize multiple nearby claims
        default: op

    claims.inspect.seeclaimsize:
        description: Allows to see the claim size with inspect tool
        default: true
    claims.inspect.seeinactivity:
        description: Allows to see the claim owner last online
        default: true
